#! /usr/bin/python
import os
import sys

def occurDict(items):
    d = {}
    for i in items:
        if i in d:
            d[i] = d[i]+1
        else:
            d[i] = 1
    return d

print (occurDict([1,2,2,3,4,5]))
